name: Deploy Docker Image to ECR

on:
  push:
    branches:
      - github-actions

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify 
        run: echo "Notification that github actions is running"

  
  build-docker-image:
    needs: notify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker build
        run: |
          echo ${{ secrets.DOCKER_IMAGE_NAME }}
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .
          echo "Image built successfully"
